name: Build, Test & Analyse

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal
  analyze:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with: 
        java-version: 11
    - name: Install dotnet-sonarscanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Install dotnet-coverage
      run: dotnet tool install --global dotnet-coverage
    - name: Sonar scan
      run: |
        dotnet sonarscanner begin /k:"bvkeersop_DocumentBuilder" /o:"bvkeersop" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
        dotnet build ./DocumentBuilder.sln --no-incremental
        dotnet-coverage collect 'dotnet test' -f xml -o 'coverage.xml'
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"