name: Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_test_analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with: 
        java-version: 11
    - name: Install dotnet-sonarscanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Install dotnet-coverage
      run: dotnet tool install --global dotnet-coverage
    - name: Sonar scan
      run: |
        dotnet sonarscanner begin /k:"bvkeersop_DocumentBuilder" /o:"bvkeersop" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
        dotnet build ./DocumentBuilder.sln --no-incremental
        dotnet-coverage collect 'dotnet test' -f xml -o 'coverage.xml'
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
  publish:
    runs-on: ubuntu-latest
    needs: build_test_analyze
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Display Version
      run: "SemVer: $GITVERSION_SEMVER"
    - name: Publish to NuGet
      id: publish_nuget
      uses: brandedoutcast/publish-nuget@v2
      with:
        PACKAGE_NAME: DocumentBuilder
        PROJECT_FILE_PATH: ./DocumentBuilder.sln
        VERSION_STATIC: $GITVERSION_SEMVER
        NUGET_KEY: ${{secrets.NUGET_KEY}}
        NUGET_SOURCE: https://api.nuget.org
    